app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/gethomepage/homepage
            tag: v0.8.8
  service:
    main:
      ports:
        http:
          port: 3000
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host home.gopherlab.win
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: homepage-tls-certificate
  persistence:
    config:
      enabled: true
      type: configMap
      name: homepage-config
      globalMounts:
        - path: /app/config/settings.yaml
          subPath: settings.yaml
        - path: /app/config/widgets.yaml
          subPath: widgets.yaml
        - path: /app/config/services.yaml
          subPath: services.yaml
        - path: /app/config/bookmarks.yaml
          subPath: bookmarks.yaml
  configMaps:
    config:
      enabled: true
      data:
        settings.yaml: |
          background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
          cardBlur: md
          theme: dark
          headerStyle: boxed
          hideVersion: true
        widgets.yaml: |
          - search:
              provider: google
              target: _blank
        services.yaml: |
          - Popular:
            - Matrix:
                href: https://chat.gopherlab.win
                description: Chat client
                icon: element.svg
            - Paperless:
                href: https://paperless.gopherlab.win
                description: Document management system
                icon: paperless.svg
          - Management:
            - Kanidm:
                href: https://auth.gopherlab.win
                description: Identity management
                icon: https://auth.gopherlab.win/pkg/img/logo-square.svg
          - Development:
            - Gitea:
                href: https://git.gopherlab.win
                description: Git forge
                icon: gitea.svg
            - Woodpecker:
                href: https://ci.gopherlab.win
                description: Continuous integration
                icon: woodpecker-ci.svg
            - ArgoCD:
                href: https://argocd.gopherlab.win
                description: Continuous deployment
                icon: argocd.svg
            - Registry:
                href: https://registry.gopherlab.win
                description: Container registry
                icon: docker.svg
            - Grafana:
                href: https://grafana.gopherlab.win
                description: Observability dashboards
                icon: grafana.svg
          - Utilities:
            - Excalidraw:
                href: https://draw.gopherlab.win
                description: Virtual whiteboard
                icon: excalidraw.svg
            - Speedtest:
                href: https://speedtest.gopherlab.win
                description: Internal network speed test
                icon: openspeedtest.png
        bookmarks.yaml: |
          - Homelab:
            - Documentation:
              - href: https://homelab.gopherlab.win
                icon: google-docs.svg
            - Public homelab repository:
              - href: https://github.com/lfleal/homelabv2
                icon: github.svg
          - Managed services:
            - Cloudflare:
              - href: https://dash.cloudflare.com
                icon: cloudflare.svg
            - Terraform Cloud:
              - href: https://app.terraform.io
                icon: terraform.svg
          - Infrastructure:
            - Router:
              - href: http://192.168.5.1
                icon: router.svg

