metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.5.11, mac: '10:62:e5:1a:f6:22', disk: sda, network_interface: eno1}
        metal1: {ansible_host: 192.168.5.12, mac: '10:62:e5:1a:33:9f', disk: sda, network_interface: eno1}
        metal2: {ansible_host: 192.168.5.13, mac: '6c:4b:90:50:fe:cf', disk: nvme0n1, network_interface: enp0s31f6}
    workers:
      hosts:
        metal3: {ansible_host: 192.168.5.14, mac: 'f4:39:09:3f:8a:71', disk: sda, network_interface: eno1}
