elementweb:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: "homelab-tunnel.gopherlab.win"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    hosts:
      - host: &frontend_host chat.gopherlab.win
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: element-tls-certificate
        hosts:
          - *frontend_host
  config:
    default:
      base_url: https://matrix.gopherlab.win
      server_name: gopherlab.win

dendrite:
  dendrite_config:
    global:
      server_name: matrix.gopherlab.win
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hostName: matrix.gopherlab.win
    tls:
      - hosts:
          - matrix.gopherlab.win
        secretName: matrix-tls-certificate
  postgresql:
    enabled: true
